services:
  twitter-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8083
    restart: unless-stopped
    container_name: twitter-mcp
    environment:
      - API_KEY=${API_KEY}
      - API_SECRET_KEY=${API_SECRET_KEY}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}

networks:
  dokploy-network:
    external: true